runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: '<database_name>'
  DATABASE_USERNAME: '<user>'
  DATABASE_PASSWORD: '<password>'
  INSTANCE_CONNECTION_NAME: '<gcp_project_name>:us-east1:<gcp_db_name>'
  SERVICE_ACCOUNT_KEY: '../../../service_account_key.json'
  GSC_BUCKET_NAME: '<bucket_name>'
  GSC_BUCKET_URL: 'https://storage.googleapis.com/<bucket_name>'
  