runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: '<database_name>'
  DATABASE_USERNAME: '<user>'
  DATABASE_PASSWORD: '<password>'
  INSTANCE_CONNECTION_NAME: '<gcp_project_name>:us-east1:<gcp_db_name>'

beta_settings:
  cloud_sql_instances: '<gcp_project_name>:us-east1:<gcp_db_name>'